name: OWASP Dependency Check

on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: Dependency Check Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build project with Maven
        run: mvn clean install

      - name: Run OWASP Dependency Check
        run: |
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v7.4.4/dependency-check-7.4.4-release.zip
          unzip dependency-check-7.4.4-release.zip
          ./dependency-check/bin/dependency-check.sh --project "test" --scan . --format "HTML" --out reports --failOnCVSS 7 --enableRetired

      - name: Upload Dependency Check report
        uses: actions/upload-artifact@v3
        with:
           name: Depcheck report
           path: 'reports/dependency-check-report.html'
